#!/bin/bash
echo "Start setup"
sudo apt-get update
echo "Installing Node"
yes | sudo apt-get install software-properties-common
yes | curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
yes | sudo apt-get install -y nodejs
yes | sudo apt-get install gcc g++ make

echo "Install Posgresql"
yes | sudo apt install postgresql postgresql-contrib libpq-dev

echo "Setting up Projects"
CURRENT=`pwd`

function setup_project() {
  # $1 is each repo
  cd $1
  C=`pwd`
  BASENAME=`basename $C`
  if [ -d "bin" ]; then
    # Control will enter here if $DIRECTORY exists.
    echo "Installing depedencies for $BASENAME"
    echo "--------"
    bin/setup
    echo "--------"
  fi
  cd ..

}

for entry in "$CURRENT"/*
do
  echo "$entry"
  if [[ -d $entry ]]; then
    setup_project $entry
  fi
done

echo "Done."
echo ""
